organization: The Harvard Crimson
name: High School Journalism Portal
address: "14 Plympton Street\nCambridge, MA 02138"
phone: (617) 576-6600
email: conference@thecrimson.com
pygments: true

coordinators:
  - name: Samir Gupta
    position: Conference Director
  - name: Dev Patel
    position: Content Director 
  - name: Samuel Weinstock
    position: Harvard Crimson President