organization: The Harvard Crimson
name: High School Journalism
address: "14 Plympton Street\nCambridge, MA 02138"
phone: (617) 576-6600
email: programs@thecrimson.com
pygments: true

president:
  name: Steven Lee
  position: Harvard Crimson President
  email: president@thecrimson.com

managingeditor:
  name: Madeline Conway
  email: managingeditor@thecrimson.com

coordinators:
  - name: "Julie Salzinger,<br /> Brian De Luna, <br />Farhana Nabi"
    position: Conference Directors
    email: programs@thecrimson.com
  - name: Christine Cahill
    position: Spring Content Director
    email: programs@thecrimson.com

spring:
  email: programs@thecrimson.com
  coordinators:
    - name: "Julie Salzinger,<br /> Brian De Luna, <br />Farhana Nabi"
      position: Conference Directors
      email: programs@thecrimson.com
      phone: (915) 256-4769
    - name: Christine Cahill
      position: Content Director
      email: programs@thecrimson.com

fall:
  email: programs@thecrimson.com
  coordinators:
    - name: "Julie Salzinger,<br /> Brian De Luna, <br />Farhana Nabi"
      position: Conference Directors
      email: programs@thecrimson.com
      phone: (915) 256-4769
    - name: Christine Cahill
      position: Content Director
      email: programs@thecrimson.com

academy:
  email: programs@thecrimson.com
  coordinators:
    - name: "Julie Salzinger,<br /> Brian De Luna, <br />Farhana Nabi"
      position: Summer Journalism Academy Directors
      email: programs@thecrimson.com
      phone: (915) 256-4769