organization: The Harvard Crimson
name: High School Journalism
address: "14 Plympton Street\nCambridge, MA 02138"
phone: (617) 576-6600
email: programs@thecrimson.com
highlighter: pygments

president:
  name: Derek K. Choi
  position: Harvard Crimson President
  email: president@thecrimson.com

managingeditor:
  name: Andrew M. Duehren
  email: managingeditor@thecrimson.com

coordinators:
  - name: "Garam Noh,<br /> Monika K. Piascik, <br />Harriet Tieh"
    position: Conference Directors
    email: programs@thecrimson.com

spring:
  email: programs@thecrimson.com
  coordinators:
  - name: "Garam Noh,<br /> Monika K. Piascik, <br />Harriet Tieh"
    position: Conference Directors
    email: programs@thecrimson.com

fall:
  email: programs@thecrimson.com
  coordinators:
  coordinators:
  - name: "Garam Noh,<br /> Monika K. Piascik, <br />Harriet Tieh"
    position: Conference Directors
    email: programs@thecrimson.com


academy:
  email: programs@thecrimson.com
  coordinators:
  coordinators:
  - name: "Garam Noh,<br /> Monika K. Piascik, <br />Harriet Tieh"
    position: Conference Directors
    email: programs@thecrimson.com