organization: The Harvard Crimson
name: Journalism Conference
address: "14 Plympton Street\nCambridge, MA 02138"
phone: (617) 576-6600
email: conference@thecrimson.com
pygments: true

coordinators:
  - name: LuShuang Xu
    position: Conference Director
  - name: Kerry Flynn
    position: Content Director 
  - name: Bobby Samuels
    position: Harvard Crimson President